name: heat_dance
description: Build with Flutter a Diet Planner.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  search_page:
  camera:
  esys_flutter_share:
  google_fonts: ^1.1.1
  flutter_launcher_icons:

  get: ^3.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true